# yamllint disable rule:line-length
# https://golangci-lint.run/usage/linters/
---
# https://golangci-lint.run/usage/configuration/#run-configuration
run:
  timeout: 3m
  issues-exit-code: 1
  tests: true
  allow-parallel-runners: false
  skip-dirs-use-default: true
  skip-dirs:
    - 'stubs'
  skip-files: []
  build-tags: []
  modules-download-mode: vendor
# https://golangci-lint.run/usage/configuration/#output-configuration
output:
  format: 'colored-line-number'
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true
# https://golangci-lint.run/usage/configuration/#linters-configuration
linters:
  disable-all: false
  enable-all: true
  fast: false
  disable:
    - tenv
    - prealloc
    - dupword
    - importas
    - varcheck
    - exhaustruct
    - exhaustivestruct
    - wrapcheck
    - varnamelen
    - goerr113
    - ireturn
    - interfacer
    - golint
    - scopelint
    - nonamedreturns
    - nosnakecase
    - nosprintfhostport
    - godot
    - gochecknoglobals
    - gochecknoinits
    - testableexamples
    - structcheck
    - inamedparam
# linters-settings {{{
# https://golangci-lint.run/usage/configuration/#linters-settings-configuration
linters-settings:
  # https://golangci-lint.run/usage/linters/#errcheck
  errcheck:
    check-type-assertions: true
    check-blank: true
    ignore: fmt:.*,io/ioutil:^Read.*
    exclude-functions:
      - io/ioutil.ReadFile
      - io.Copy(*bytes.Buffer)
      - io.Copy(os.Stdout)
  # https://golangci-lint.run/usage/linters/#gosimple
  gosimple:
    # https://staticcheck.dev/docs/configuration/options/#checks
    checks: ['all']
  # https://golangci-lint.run/usage/linters/#govet
  govet:
    check-shadowing: true
    enable-all: true
    disable-all: false
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
      shadow:
        strict: true
  # https://golangci-lint.run/usage/linters/#staticcheck
  staticcheck:
    # https://staticcheck.dev/docs/configuration/options/#checks
    checks: ['all']
  # https://golangci-lint.run/usage/linters/#asasalint
  asasalint:
    use-builtin-exclusions: true
    ignore-test: false
  # https://golangci-lint.run/usage/linters/#bidichk
  bidichk:
    left-to-right-embedding: true
    right-to-left-embedding: true
    pop-directional-formatting: true
    left-to-right-override: true
    right-to-left-override: true
    left-to-right-isolate: true
    right-to-left-isolate: true
    first-strong-isolate: true
    pop-directional-isolate: true
  # https://golangci-lint.run/usage/linters/#cyclop
  cyclop:
    max-complexity: 30
    package-average: 0.0
    skip-tests: false
  # https://golangci-lint.run/usage/linters/#decorder
  decorder:
    dec-order:
      - type
      - const
      - var
      - func
    disable-dec-order-check: false
    disable-init-func-first-check: false
    disable-dec-num-check: true
  # https://golangci-lint.run/usage/linters/#depguard
  depguard:
    list-type: denylist
    include-go-root: false
    packages:
      - github.com/sirupsen/logrus
    packages-with-error-message:
      - github.com/sirupsen/logrus: 'logging is allowed only by logutils.Log'
    rules:
      logger:
        deny:
          - pkg: 'github.com/sirupsen/logrus'
            desc: 'not allowed'
          - pkg: 'github.com/pkg/errors'
            desc: 'Should be replaced by standard lib errors package'
  # https://golangci-lint.run/usage/linters/#dogsled
  dogsled:
    max-blank-identifiers: 2
  # https://golangci-lint.run/usage/linters/#dupl
  dupl:
    threshold: 300
  # https://golangci-lint.run/usage/linters/#errchkjson
  errchkjson:
    check-error-free-encoding: true
    report-no-exported: true
    exclude-functions:
      - encoding/json.Marshal
      - encoding/json.MarshalIndent
  # https://golangci-lint.run/usage/linters/#errorlint
  errorlint:
    errorf: true
    errorf-multi: false
    asserts: true
    comparison: true
  # https://golangci-lint.run/usage/linters/#exhaustive
  exhaustive:
    check: ['switch', 'map']
    check-generated: false
    default-signifies-exhaustive: true
    package-scope-only: false
    explicit-exhaustive-switch: false
    explicit-exhaustive-map: false
  # https://golangci-lint.run/usage/linters/#forbidigo
  forbidigo:
    forbid:
      - '^print.*$'
      - 'fmt\.Print.*'
    exclude_godoc_examples: false
    analyze-types: true
  # https://golangci-lint.run/usage/linters/#funlen
  funlen:
    lines: 240
    statements: 120
  # https://golangci-lint.run/usage/linters/#gci
  gci:
    skip-generated: true
    no-inline-comments: true
    no-prefix-comments: true
    custom-order: true
    sections:
      - standard
      - default
      - prefix(github.com/agurinov/gopl)
    section-separators: ['newLine']
  # https://golangci-lint.run/usage/linters/#gocognit
  gocognit:
    min-complexity: 35
  # https://golangci-lint.run/usage/linters/#goconst
  goconst:
    min-len: 3
    min-occurrences: 3
    ignore-tests: false
    match-constant: true
    numbers: false
    ignore-calls: true
  # https://golangci-lint.run/usage/linters/#gocritic
  # https://go-critic.com/overview#checks-overview
  gocritic:
    enabled-checks: []
    disabled-checks:
      - regexpMust
      - ifElseChain
      - hugeParam
      - unnamedResult
    enabled-tags:
      - style
      - performance
    disabled-tags:
      - opinionated
      - experimental
    settings:
      captLocal:
        paramsOnly: true
      elseif:
        skipBalanced: true
      hugeParam:
        sizeThreshold: 320
      nestingReduce:
        bodyWidth: 5
      rangeExprCopy:
        sizeThreshold: 512
        skipTestFuncs: false
      rangeValCopy:
        sizeThreshold: 32
        skipTestFuncs: false
      ruleguard: {}
      truncateCmp:
        skipArchDependent: true
      underef:
        skipRecvDeref: false
  # https://golangci-lint.run/usage/linters/#gocyclo
  gocyclo:
    min-complexity: 30
  # https://golangci-lint.run/usage/linters/#godox
  godox:
    keywords:
      - FIXME
      - BUG
      - CRITICAL
  # https://golangci-lint.run/usage/linters/#gofmt
  gofmt:
    simplify: true
    rewrite-rules:
      - pattern: 'interface{}'
        replacement: 'any'
      - pattern: 'a[b:len(a)]'
        replacement: 'a[b:]'
  # https://golangci-lint.run/usage/linters/#gofumpt
  gofumpt:
    module-path: 'github.com/agurinov/gopl'
    extra-rules: false
  # https://golangci-lint.run/usage/linters/#goimports
  goimports:
    local-prefixes: 'github.com/agurinov/gopl'
  # https://golangci-lint.run/usage/linters/#golint
  golint:
    min-confidence: 0.8
  # https://golangci-lint.run/usage/linters/#gomnd
  # https://github.com/tommy-muehle/go-mnd/#checks
  gomnd:
    settings:
      mnd:
        checks:
          - argument
          - case
          - condition
          - operation
          - return
          - assign
        ignored-numbers:
          - '0666'
          - '0755'
        ignored-files: []
        ignored-functions: []
  # https://golangci-lint.run/usage/linters/#gomoddirectives
  gomoddirectives:
    replace-local: false
    replace-allow-list: []
    retract-allow-no-explanation: false
    exclude-forbidden: false
  # https://golangci-lint.run/usage/linters/#gomodguard
  gomodguard:
    allowed:
      modules: []
      domains: []
    blocked:
      local_replace_directives: false
      modules: []
      versions: []
  # https://golangci-lint.run/usage/linters/#gosec
  # https://github.com/securego/gosec#available-rules
  # https://github.com/securego/gosec#configuration
  gosec:
    includes: []
    excludes: []
    exclude-generated: false
    severity: 'low'
    confidence: 'low'
    config:
      global:
        nosec: true
        show-ignored: true
        audit: true
      G306: '0600'
      G101:
        pattern: '(?i)passwd|pass|password|pwd|secret|private_key|privateKey|token|pw|apiKey|bearer|cred'
        ignore_entropy: true
        truncate: '32'
  # https://golangci-lint.run/usage/linters/#grouper
  grouper:
    const-require-single-const: false
    const-require-grouping: false
    import-require-single-import: false
    import-require-grouping: false
    type-require-single-type: false
    type-require-grouping: false
    var-require-single-var: false
    var-require-grouping: false
  # https://golangci-lint.run/usage/linters/#ifshort
  ifshort:
    max-decl-lines: 1
    max-decl-chars: 30
  # https://golangci-lint.run/usage/linters/#lll
  lll:
    line-length: 100
    tab-width: 1
  # https://golangci-lint.run/usage/linters/#maintidx
  # https://docs.microsoft.com/en-us/visualstudio/code-quality/code-metrics-maintainability-index-range-and-meaning?view=vs-2022
  # https://github.com/yagipy/maintidx
  maintidx:
    under: 30
  # https://golangci-lint.run/usage/linters/#maligned
  maligned:
    suggest-new: true
  # https://golangci-lint.run/usage/linters/#nakedret
  nakedret:
    max-func-lines: 100
  # https://golangci-lint.run/usage/linters/#nestif
  nestif:
    min-complexity: 5
  # https://golangci-lint.run/usage/linters/#nilnil
  nilnil:
    checked-types:
      - ptr
      - func
      - iface
      - map
      - chan
  # https://golangci-lint.run/usage/linters/#nlreturn
  nlreturn:
    block-size: 1
  # https://golangci-lint.run/usage/linters/#nolintlint
  nolintlint:
    allow-unused: false
    allow-leading-space: false
    allow-no-explanation: []
    require-explanation: false
    require-specific: true
  # https://golangci-lint.run/usage/linters/#paralleltest
  paralleltest:
    ignore-missing: true
  # https://golangci-lint.run/usage/linters/#predeclared
  predeclared:
    ignore: ''
    q: true
  # https://golangci-lint.run/usage/linters/#promlinter
  # https://github.com/yeya24/promlinter#usage
  promlinter:
    strict: true
    disabled-linters: []
  # https://golangci-lint.run/usage/linters/#reassign
  reassign:
    patterns:
      - '.*'
  # https://golangci-lint.run/usage/linters/#revive
  # https://github.com/mgechev/revive#available-rules
  revive:
    enable-all-rules: true
    ignore-generated-header: true
    severity: warning
    min-confidence: 0.8
    rules:
      - {name: 'file-header', disabled: true}
      - {name: 'line-length-limit', disabled: true}
      - {name: 'banned-characters', disabled: true}
      - {name: 'function-length', disabled: true}
      - {name: 'if-return', disabled: true}
      - {name: 'confusing-naming', disabled: true}
      - {name: 'import-alias-naming', disabled: true}
      - name: cyclomatic
        arguments: 15
      - name: cognitive-complexity
        arguments: 20
      - name: argument-limit
        arguments: 8
      - name: function-result-limit
        arguments: 3
      - name: max-public-structs
        arguments: 6
      - name: add-constant
        arguments:
          maxLitCount: '5'
          allowInts: '0,1,2'
  # https://golangci-lint.run/usage/linters/#rowserrcheck
  rowserrcheck:
    packages:
      - github.com/jmoiron/sqlx
  # https://golangci-lint.run/usage/linters/#stylecheck
  # https://staticcheck.io/docs/options#checks
  stylecheck:
    checks: ['all', '-ST1000', '-ST1003', '-ST1016', '-ST1020', '-ST1021', '-ST1022']
    dot-import-whitelist: []
    http-status-code-whitelist: []
  # https://golangci-lint.run/usage/linters/#tagalign
  tagalign:
    align: false
    sort: true
    order:
      - json
      - yaml
      - yml
      - toml
      - validate
  # https://golangci-lint.run/usage/linters/#tagliatelle
  tagliatelle:
    case:
      use-field-name: false
      rules:
        json: snake
  # https://golangci-lint.run/usage/linters/#tenv
  tenv:
    all: false
  # https://golangci-lint.run/usage/linters/#thelper
  thelper:
    test: {first: true, name: true, begin: true}
    benchmark: {first: true, name: true, begin: true}
    tb: {first: true, name: true, begin: true}
    fuzz: {first: true, name: true, begin: true}
  # https://golangci-lint.run/usage/linters/#wsl
  # https://github.com/bombsimon/wsl/blob/master/doc/configuration.md
  wsl:
    strict-append: true
    allow-assign-and-anything: false
    allow-assign-and-call: true
    allow-cuddle-declarations: false
    allow-multiline-assign: true
    allow-separated-leading-comment: false
    allow-trailing-comment: false
    force-case-trailing-whitespace: 0
    force-err-cuddling: true
    error-variable-names: ['err']
    force-short-decl-cuddling: false
# }}}

# issues {{{
# https://golangci-lint.run/usage/configuration/#issues-configuration
issues:
  include: []
  exclude: []
  exclude-use-default: true
  exclude-case-sensitive: false
  exclude-rules:
    - path: '_test\.go'
      linters:
        - funlen
        - gocyclo
        - dupl
        - gosec
        - govet
        - revive
        - maintidx
    - source: '^//go:generate '
      linters:
        - lll
    - source: '^(\s)*// '
      linters:
        - lll
  max-issues-per-linter: 5
  max-same-issues: 5
  new: false
  fix: false
# }}}

# severity {{{
# https://golangci-lint.run/usage/configuration/#severity-configuration
severity:
  default-severity: error
  case-sensitive: false
  rules:
    - severity: info
      linters:
        - dupl
# }}}
