// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockery

import (
	"context"

	"github.com/agurinov/gopl/fsm"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStateStorage creates a new instance of MockStateStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStateStorage[C fsm.Context](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStateStorage[C] {
	mock := &MockStateStorage[C]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStateStorage is an autogenerated mock type for the StateStorage type
type MockStateStorage[C fsm.Context] struct {
	mock.Mock
}

type MockStateStorage_Expecter[C fsm.Context] struct {
	mock *mock.Mock
}

func (_m *MockStateStorage[C]) EXPECT() *MockStateStorage_Expecter[C] {
	return &MockStateStorage_Expecter[C]{mock: &_m.Mock}
}

// GetState provides a mock function for the type MockStateStorage
func (_mock *MockStateStorage[C]) GetState(context1 context.Context, v C) (fsm.State, error) {
	ret := _mock.Called(context1, v)

	if len(ret) == 0 {
		panic("no return value specified for GetState")
	}

	var r0 fsm.State
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, C) (fsm.State, error)); ok {
		return returnFunc(context1, v)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, C) fsm.State); ok {
		r0 = returnFunc(context1, v)
	} else {
		r0 = ret.Get(0).(fsm.State)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, C) error); ok {
		r1 = returnFunc(context1, v)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStateStorage_GetState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetState'
type MockStateStorage_GetState_Call[C fsm.Context] struct {
	*mock.Call
}

// GetState is a helper method to define mock.On call
//   - context1 context.Context
//   - v C
func (_e *MockStateStorage_Expecter[C]) GetState(context1 interface{}, v interface{}) *MockStateStorage_GetState_Call[C] {
	return &MockStateStorage_GetState_Call[C]{Call: _e.mock.On("GetState", context1, v)}
}

func (_c *MockStateStorage_GetState_Call[C]) Run(run func(context1 context.Context, v C)) *MockStateStorage_GetState_Call[C] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 C
		if args[1] != nil {
			arg1 = args[1].(C)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStateStorage_GetState_Call[C]) Return(state fsm.State, err error) *MockStateStorage_GetState_Call[C] {
	_c.Call.Return(state, err)
	return _c
}

func (_c *MockStateStorage_GetState_Call[C]) RunAndReturn(run func(context1 context.Context, v C) (fsm.State, error)) *MockStateStorage_GetState_Call[C] {
	_c.Call.Return(run)
	return _c
}

// PushState provides a mock function for the type MockStateStorage
func (_mock *MockStateStorage[C]) PushState(context1 context.Context, v C, state fsm.State) error {
	ret := _mock.Called(context1, v, state)

	if len(ret) == 0 {
		panic("no return value specified for PushState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, C, fsm.State) error); ok {
		r0 = returnFunc(context1, v, state)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStateStorage_PushState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PushState'
type MockStateStorage_PushState_Call[C fsm.Context] struct {
	*mock.Call
}

// PushState is a helper method to define mock.On call
//   - context1 context.Context
//   - v C
//   - state fsm.State
func (_e *MockStateStorage_Expecter[C]) PushState(context1 interface{}, v interface{}, state interface{}) *MockStateStorage_PushState_Call[C] {
	return &MockStateStorage_PushState_Call[C]{Call: _e.mock.On("PushState", context1, v, state)}
}

func (_c *MockStateStorage_PushState_Call[C]) Run(run func(context1 context.Context, v C, state fsm.State)) *MockStateStorage_PushState_Call[C] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 C
		if args[1] != nil {
			arg1 = args[1].(C)
		}
		var arg2 fsm.State
		if args[2] != nil {
			arg2 = args[2].(fsm.State)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStateStorage_PushState_Call[C]) Return(err error) *MockStateStorage_PushState_Call[C] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStateStorage_PushState_Call[C]) RunAndReturn(run func(context1 context.Context, v C, state fsm.State) error) *MockStateStorage_PushState_Call[C] {
	_c.Call.Return(run)
	return _c
}
