// Code generated by "stringer -type=EventHandleStrategy ."; DO NOT EDIT.

package kafka

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EventHandleOneByOne-0]
	_ = x[EventHandleBatch-1]
}

const _EventHandleStrategy_name = "EventHandleOneByOneEventHandleBatch"

var _EventHandleStrategy_index = [...]uint8{0, 19, 35}

func (i EventHandleStrategy) String() string {
	if i >= EventHandleStrategy(len(_EventHandleStrategy_index)-1) {
		return "EventHandleStrategy(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventHandleStrategy_name[_EventHandleStrategy_index[i]:_EventHandleStrategy_index[i+1]]
}
