---
name: 'Golang library jobs'
run-name: 'Golang library jobs'

on:
  push:
  workflow_call:

jobs:
  code-quality:
    name: 'go${{ matrix.go-version }} | gomake ${{ matrix.gomake-target }}'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        go-version: ['1.18.10', '1.19.13', '1.20.10', '1.21.3']
        gomake-target: ['go_test']
        include:
          - go-version: '1.20.10'
            gomake-target: 'lint'
          - go-version: '1.21.3'
            gomake-target: 'lint'
    steps:
      - uses: actions/checkout@v3
      - uses: agurinov/pipelines/github-actions/actions/setup-dotfiles@main
        with:
          token: ${{ secrets.DOTFILES_GITHUB_TOKEN }}
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - run: make --include-dir=~/.make --no-print-directory toolset-ci
        env:
          GO: /opt/hostedtoolcache/go/${{ matrix.go-version }}/x64/bin/go
          GO_VERSION: ${{ matrix.go-version }}
          BINDIR: ${HOME}/go/bin
        working-directory: .dotfiles/golang
      - run: make --include-dir=~/.make --no-print-directory -f ~/.make/golang.mk ${{ matrix.gomake-target }}
...
