---
name: 'Bump tag version'
run-name: 'Bump tag version'

on:
  workflow_run:
    workflows:
      - 'golang'
    branches:
      - master
      - main
    types:
      - completed

jobs:
  tag-version:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
...
